name: Check scripts

on:
  push:

jobs:
  check-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check scripts with shellcheck
        run: shellcheck -a -C --shell sh scripts/*.sh

